pipeline {
  agent any
  tools {
    maven 'apache-maven-3.6.1'
  }
  stages {
    stage('Unit Test') { 
      steps {
        sh 'mvn clean test'
      }
    }
    
    stage('Deploy Standalone') { 
      steps {
        sh 'mvn deploy -P standalone -DmuleDeploy'
      }
    }
    

    
    stage('Deploy CloudHub') { 
      environment {
        ANYPOINT_CREDENTIALS = credentials('anypoint.credentials')
      }
      steps {
        sh 'mvn deploy -P cloudhub -DmuleDeploy -Danypoint.username=${ANYPOINT_CREDENTIALS_USR}  -Danypoint.password=${ANYPOINT_CREDENTIALS_PSW}' 
      }
    }
  }
}